apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-gnrn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-gnrn
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-gnrn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-gnrn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-gnrn
    spec:
      containers:
      - image: quay.io/tnevrlka-test/release-e2e-deploy-tenant/appstudio/dc-metro-map-gnrn@sha256:fe35f42b9993fe5361385a6eee715381af17baece0f60334eedccb8d6af22c1c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
